### ISSUE TITLE
Add numba to speed up python in the performance test

### ISSUE THREAD

**Issue by woodwm** [LakeTide/share#1]
Hello,

I see your post in Julia discourse. I tried your code in Julia and Python. I also get similar result, actually longer time than yours because of the computer performance, with python needs more than 7 min while Julia needs about 3 second. It is really amazing and I feel also a little disappointed about python performance. So I tried `numba`, simply add `@jit` before the function, then the total running time reduced to about 3 second too. That is it. Python is still not too bad.

**Comment by r3tex** [comment]
Yep! Numba is pretty good. Then you want to use a list or a dict or a custom class and everything is slow again.

**Comment by woodwm** [comment]
I know `numba` is not perfect and Julia usually have a good performance. Just to be fare, for the example case in your code, python still have ways to run fast.

**Comment by r3tex** [comment]
The point of the article is simply that you get a lot with very little effort in Julia.

**Comment by Petterhg** [comment]
It is time.


On 8 Feb 2019, at 16:25, Robert Luciani <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/LakeTide/share/issues/1>.
